# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-foundries"
BBFILE_PATTERN_meta-foundries = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-foundries = "6"

LAYERDEPENDS_meta-foundries = "core openembedded-layer meta-python \
                               filesystems-layer sota"
LAYERSERIES_COMPAT_meta-foundries = "blacksail wrynose"

include conf/fio-documentation.conf
