header:
  version: 14

target: core-image-minimal

repos:
  meta-foundries:
    layers:
      .:

  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: master
    layers:
      .: disabled

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: master
    layers:
      meta:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: master
    layers:
      meta-oe:
      meta-python:
      meta-filesystems:
      meta-networking:

  meta-updater:
    url: https://github.com/uptane/meta-updater
    branch: master
    layers:
      .:

local_conf_header:
  base: |
    CONF_VERSION = "2"
    DISTRO = "nodistro"
    # Add size metadata to OSTree commit objects, allowing update size estimation
    EXTRA_OSTREE_COMMIT += "--generate-sizes"

  fio-device-register: |
    LMP_FACTORY ?= "default"
    LMP_FACTORY_TAG ?= "master"
    OS_RELEASE_FIELDS:append = " LMP_FACTORY LMP_FACTORY_TAG"
    SOTA_CLIENT ?= "aktualizr-lite"
