name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on:
      group: GHA-prd-foundriesio-SelfHosted-RG
      labels: [ self-hosted, qcom-u2404, amd64 ]
    steps:
      - uses: actions/checkout@v7
      - uses: vale-cli/vale-action@v3.0.0
        with:
         files: docs/
         reporter: github-pr-check
         fail_on_error: false
         token: ${{secrets.GITHUB_TOKEN}}
         vale_flags: "--config=docs/.vale.ini"
